# Generated by Django 5.1.6 on 2025-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2025-03-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='dsadsada', max_length=128),
            preserve_default=False,
        ),
    ]
