# Generated by Django 5.1.6 on 2025-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='adm', max_length=32),
            preserve_default=False,
        ),
    ]
